### ISSUE TITLE
Travamento na tela de seleção do modulo

### ISSUE THREAD

**Issue by FAVIOSENGER** [totvs/tir#1000]
Ao utilizar a variavel de idioma no config.json ("Language": "es-es") o TIR fica travado na tela de seleção de modulo e não continua.
Ja estamos com a webapp 9.0.2

**To Reproduce**
Defina o idioma espanhol na linguagem do config.json

**Comment by HelenaAdrignoli** [comment]
Foi realizado tratamento para considerar o parâmetro do config.json e o mesmo estará disponível na próxima release da branch Master.

**Comment by FAVIOSENGER** [comment]
Bom dia, quando vai ser liberada a nova versão?

De: Helena ***@***.***>
Enviada em: quarta-feira, 21 de dezembro de 2022 13:59
Para: totvs/tir ***@***.***>
Cc: FAVIOSENGER ***@***.***>; Author ***@***.***>
Assunto: Re: [totvs/tir] Travamento na tela de seleção do modulo (Issue #1000)


Closed #1000<https://github.com/totvs/tir/issues/1000> as completed.
