### ISSUE TITLE
Erro ao usar a função ClickFolder

### ISSUE THREAD

**Issue by GuilhermeAs7** [totvs/tir#1119]
**Describe the bug**
Ao tentar realizar o cadastro existem pastas e subpastas que possuem campo de preenchimento obrigatório. Dentro da pasta Principal possuímos a pasta Fiscais e essa não consegue ser acessada. Não existe em tela outra pasta com mesmo nome e nem botão. A mensagem de erro é que não foi possível encontrar essa e qualquer outra pasta.

**Screenshots**
![image](https://user-images.githubusercontent.com/32078978/224240462-88af8db3-a304-419b-bfa8-14f3d7ba5d20.png)

**Comment by HelenaAdrignoli** [comment]
Bom dia Guilherme! Consegue me informar qual rotina acontece essa situação?

**Comment by HelenaAdrignoli** [comment]
Bom dia! As correções para a está issue estarão disponíveis na próxima branch master. Estamos encerrando está task.
