### ISSUE TITLE
Login não está sendo realizado na versão 2210

### ISSUE THREAD

**Issue by NPRlombardi** [totvs/tir#1177]
Descrição
Boa Tarde, estou tentando utilizar o TIR com a versão 2210 e está dando a mensagem do log anexo, fiz o teste usando o ambiente 33 e está funcionando normal.

Mensagem do erro:
setUpClass - Wasn't   possible execute Start() method: Unable to find a matching set of   capabilities

Reproduzir
1. Config padrão de usuario e senha, ambiente
2. Rodar o script
3. Carrega o webapp e coloca o env e a rotina
4. Para na tela de login, não trava mas não digita.

Esperado
Logar no sistema

Captura de tela
![image](https://github.com/totvs/tir/assets/86851639/fcdaef89-fd8b-4876-883f-4398d81c254b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Firefox
 - Protheus 12.1.2210

**Additional context**
[rodrigo_lombardi_04d88d5802244249b4d628748eb9bd7e_auto.csv](https://github.com/totvs/tir/files/11579762/rodrigo_lombardi_04d88d5802244249b4d628748eb9bd7e_auto.csv)

**Comment by HelenaAdrignoli** [comment]
Bom dia @NPRlombardi!!

No AppServer.ini você está usando o parâmetro App_Environment=SEUENVIROMENT ?
E no config.json você está usando o parâmetro "POUILogin": true?

Pergunto isso pois ambos são necessário para conseguir executar na 2210.

Aguardo retorno.

**Comment by NPRlombardi** [comment]
Bom dia @HelenaAdrignoli ,

Acabei encontrando no chat do Gitter esse parâmetro POUILogin e colocando como true e atualizando para a versão 1.20.5 o login ocorreu perfeitamente.

Na versão 1.20.4 estava dando erro na hora de colocar a database mesmo com o parametro POUILogin como true, porem bastou atualizar e resolveu.

Esse parâmetro ainda não consta nos docs do config.json correto?

Obrigado pelo retorno!

**Comment by HelenaAdrignoli** [comment]
@NPRlombardi que bom que deu certo! Disponibilizaremos em breve a documentação relacionada ao POUI.

Obrigada
Estou encerrando a issue.
