### ISSUE TITLE
Servidor Não Está Respondendo - DashBoard

### ISSUE THREAD

**Issue by renfreire** [totvs/tir#1258]
**Describe the bug**
Mensagem de erro ao tentar acessar o Status dos Testes no Painel da Qualidade.

**To Reproduce**
1 - Abrir o Portal da Qualidade
2 - Clicar no menu Status
3 - O loading de carregamento abre na tela mas logo aparece a barra de erro sinalizando o erro do print abaixo

**Screenshots**
![image](https://github.com/totvs/tir/assets/25564702/67aa632e-f4a4-4a56-acb4-f91cf43c45f1)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Firefox 
 - Version 116.0.3 (64 bits) 
 - Database: MS SQL Server

**Additional context**
A instação do TIR foi concluida e os scripts rodam perfeitamente. Apenas essa questão do portal que não está funcionando corretamente. Ambiente com as últimas atualizações do servicelog api e front

**Comment by renanllisboa** [comment]
Boa tarde,

Verifique as configurações abaixo:

Observações
A porta do web server deve ser a mesma APP_PORT configurada arquivo .env. Nesse caso fica no arquivo html/config/appConfig.json
