### ISSUE TITLE
TIR-RECORD no Chrome

### ISSUE THREAD

**Issue by tirabassi** [totvs/tir#1411]
**A solicitação de recurso está relacionada a um problema? Por favor, descreva.**
Sim. Atualmente, a ferramenta TIR da Totvs oferece um plugin para o navegador Firefox (TIR-RECORD) que facilita a gravação de ações do usuário para criar scripts de teste automatizados no Protheus. No entanto, na nossa empresa, por questões de política interna, só é permitido o uso do navegador Google Chrome, o que nos impede de utilizar o plugin de gravação fornecido pela TIR. Isso se torna um problema pois limita nossa capacidade de automatizar testes de maneira eficiente, visto que não podemos utilizar o recurso de gravação que agiliza significativamente o processo de criação de testes.

**Descreva a solução que você gostaria**
Gostaríamos que o plugin de gravação disponível para o Firefox fosse também desenvolvido e disponibilizado para o Google Chrome, permitindo assim que equipes que utilizam o Chrome como seu navegador padrão possam se beneficiar da mesma facilidade na criação de scripts de teste automatizados para o Protheus. Isso não apenas ampliaria o alcance da ferramenta TIR, mas também facilitaria a adoção e o uso da mesma em ambientes onde o Chrome é o navegador padrão.

**Descreva alternativas que você considerou**
Como alternativa, caso o desenvolvimento de um plugin para o Chrome não seja viável no momento, gostaríamos de solicitar o acesso ao código-fonte do plugin atual para o Firefox. Isso nos permitiria avaliar a possibilidade de portar o plugin internamente para o Chrome, adaptando-o às nossas necessidades específicas. Entendemos que isso envolve considerações de licenciamento e propriedade intelectual, mas estamos abertos a discutir essas questões para encontrar uma solução que beneficie ambas as partes.

**Contexto adicional**
A falta de uma ferramenta de gravação para o Chrome nos obriga a criar os scripts de teste manualmente, o que é consideravelmente mais demorado e suscetível a erros. Acreditamos que a disponibilização desse recurso para o Chrome não apenas otimizaria nossos processos de desenvolvimento e teste, mas também poderia incentivar outras empresas com restrições semelhantes a adotar a ferramenta TIR para automação de testes no Protheus.

**Comment by renanllisboa** [comment]
Boa tarde, não esta previsto para disponibilizar para o Chrome e nem disponibilizar o código fonte. Você pode tentar utilizar os scripts que subimos no nosso repositório de exemplos.
https://github.com/totvs/tir?tab=readme-ov-file#samples
