### ISSUE TITLE
Problema de Conexão do TIR com Usuário Admin sem Senha

### ISSUE THREAD

**Issue by carloseniemeyer** [totvs/tir#1444]
**Descrição do Erro**
Erro ao Fazer Login com Usuário Admin sem Senha.
Se ficar com senha " " no config.json fica piscando a tela e não clica no botão para acessar.
Se ficar com senha "" no config.json paralisa o script e não prossegue

**Configurações:**

**config.json:**
```
{
"Url": "http://localhost:8089/",
"Browser": "Firefox",
"Environment": "WORK_NIEMEYER_ORACLE_DEV1",
"Language": "pt-br",
"User": "admin",
"Password": " ",
"Headless": false,
"DebugLog": false,
"POUILogin": true,
"ScreenshotFolder": "C:\TIR\tir-script-samples\Log",
"ScreenShot": false,
"NewLog": true
}
```

**Para reproduzir:**
- Faça download do tir-script-samples
- Configure o config.json com usuário Admin sem senha (Vazio) ou 
- Utilize o WebApp com POUI ativado e configure o config.json com POUILogin = true
- Execute um script

**Comportamento Esperado**
- Conectar o Protheus com usuário Admin sem senha

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: firefox
 - Version: TIR framework - 1.20.20

**Dados do: pip freeze**

alabaster==0.7.13
Babel==2.14.0
beautifulsoup4==4.12.2
certifi==2024.6.2
charset-normalizer==3.3.2
colorama==0.4.6
docutils==0.19
enum34==1.1.10
idna==3.7
imagesize==1.4.1
importlib-metadata==6.7.0
Jinja2==3.1.4
lxml==4.6.5
MarkupSafe==2.1.5
numpy==1.21.6
opencv-python==4.6.0.66
packaging==24.0
pandas==1.0.1
psutil==5.9.5
Pygments==2.17.2
pyodbc==4.0.39
python-dateutil==2.8.2
python-dotenv==0.21.1
pytz==2023.3
requests==2.29.0
selenium==3.8.0
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.4.1
Sphinx==5.3.0
sphinx-rtd-theme==2.0.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
tir-framework==1.20.20
typing_extensions==4.7.1
urllib3==1.26.19
webdriver-manager==4.0.1
zipp==3.15.0

**Imagens GIF do Processo**
![TesteLoginUsuarioSemSenhaComHeadLessTrue](https://github.com/totvs/tir/assets/52763295/78313c91-e4d4-4d57-8c6e-4dce1a729f75)

![ErroLoginTIRUsuarioSemSenha](https://github.com/totvs/tir/assets/52763295/3d8cd8d1-f46c-47b3-a6d9-67f19139918f)

**Comment by renanllisboa** [comment]
Bom dia,

Verificamos que o preenchimento do login com usuário e senha = "" só funciona para o login que não seja em POUI.  Somente é aceito " " aspas com um espaço em branco.

No momento precisamos tratar isso no TIR, caso queira fazer um contorno, desative o login em POUI e prossiga com os testes.

Atenciosamente

**Comment by renanllisboa** [comment]
Boa tarde,

A correção para está não conformidade já encontra-se disponível na branch "develop". Favor atualizar o TIR e realizar um novo teste.

Para executar o comando abaixo é necessário ter o "git" instalado .

Git:
https://git-scm.com/downloads

Atualize utilizando o comando "pip install git+https://github.com/totvs/tir.git@develop --upgrade"
TIR Release: 1.20.21rc3

Para verificar o release, abra o prompt de comando e digite "pip show tir_framework"

Está correção estará disponível na master na próxima janela de atualização.
