### ISSUE TITLE
Problema ao concatenar variáveis de conversão de data e executar QueryExecute

### ISSUE THREAD

**Issue by caiquess** [totvs/tir#1452]
Tento concatenar variáveis de data convertida em string em uma CONSULTA para executar o QueryExecute e apresenta erro de DeprecationWarning: `np.bool`

Ex ERRO - SS13
![Screenshot_13](https://github.com/totvs/tir/assets/46875593/6fa87da4-b82c-4359-925e-96514162afae)

Quando é passada as avariáveis em string "digitada" o script segue normalmente.
Ex OK -  SS14
![Screenshot_14](https://github.com/totvs/tir/assets/46875593/a8fd755e-4daf-4d14-ac77-66a28ce95171)

**Comment by caiquess** [comment]
Boa tarde,

Estou usando o padrão extraído do GIT.
Eu tentei desativar o warning, mas mesmo assim parava o processo.

segue resultado do comando:
PS C:\Users\caique.silva\Music\GIT_TIR_SCRIPTS\tir-script-samples> pip
freeze
beautifulsoup4==4.12.2
certifi==2024.6.2
charset-normalizer==3.3.2
enum34==1.1.10
idna==3.7
lxml==4.6.5
numpy==1.21.6
opencv-python==4.6.0.66
packaging==24.0
pandas==1.0.1
psutil==5.9.5
pyodbc==4.0.39
python-dateutil==2.8.2
python-dotenv==0.21.1
pytz==2023.3
requests==2.29.0
selenium==3.8.0
six==1.16.0
soupsieve==2.4.1
tir-framework==1.20.20
urllib3==1.26.19
webdriver-manager==4.0.1

Atenciosamente,

Caíque de Souza Silva
+55 71 9 9197 6129


Em qui., 18 de jul. de 2024 às 16:20, Renan Lacerda Lisboa <
***@***.***> escreveu:

**Comment by renanllisboa** [comment]
Bom dia,

Esta correto a versão da lib.

Poderia mandar o script que esta utilizando?

Precisamos avaliar o objeto data.

Atenciosamente

**Comment by renanllisboa** [comment]
Bom dia,

Com este cenário não consegui reproduzir o problema, quer deixar o seu e-mail para que possamos entrar em contato e marcar um call?

Pode deixar uma mensagem privada no gitter por questões de privacidade.

Atenciosamente
