### ISSUE TITLE
Error using Scrollgrid

### ISSUE THREAD

**Issue by edusfc15** [totvs/tir#147]
I've got a problem when I was trying to use the Scrollgrid method.

The error is the following:
`"Traceback (most recent call last):
  File "d:\testes_protheus\TESTS\SIGAGPE\GPEA180\test_GPEA180.py", line 48, in test_transferencia
    self.oHelper.ScrollGrid(column="Dt.Transfer.", match_value=self.dataref)
  File "C:\Users\02890389103\AppData\Local\Programs\Python\Python37\lib\site-packages\tir\main.py", line 372, in ScrollGrid
    self.__webapp.ScrollGrid(column, match_value, grid_number)
  File "C:\Users\02890389103\AppData\Local\Programs\Python\Python37\lib\site-packages\tir\technologies\webapp_internal.py", line 2363, in ScrollGrid
    current = get_current()
  File "C:\Users\02890389103\AppData\Local\Programs\Python\Python37\lib\site-packages\tir\technologies\webapp_internal.py", line 2362, in <lambda>
    get_current = lambda: self.get_grid(grid_number).select("tbody tr.selected-row")[0]
IndexError: list index out of range" `

And the code:

```
from tir import Webapp
import unittest
from os import getcwd
from datetime import date


class GPEA180(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        self.filial = '02DF0001'
        self.mat = '227909'
        self.dataref = date.today().strftime("%d/%m/%Y")

        configfile = getcwd() + '\\config.json'
        self.oHelper = Webapp(configfile)
        self.oHelper.Setup('SIGAGPE', self.dataref, '02', self.filial, '07')
        self.oHelper.SetLateralMenu(
            "Atualizações > Funcionários > Transferências")

    def test_transferencia(self):

        self.oHelper.SearchBrowse(self.filial + self.mat)

        self.oHelper.SetButton('Visualizar')
        self.oHelper.LoadGrid()
        self.oHelper.ScrollGrid(column="Dt.Transfer.", match_value=self.dataref) 

        print("")

    @classmethod
    def tearDownClass(self):
        self.oHelper.TearDown()


if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTest(GPEA180('test_transferencia'))

    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)

```

**Comment by Wilson08** [comment]
Olá, @edusfc15.
Você já tentou executar com o novo release do TIR (1.13.0) ?

**Comment by edusfc15** [comment]
@Wilson08 vou testar, e te retorno...

**Comment by Wilson08** [comment]
@edusfc15 , você conseguiu realizar o teste  ?

**Comment by edusfc15** [comment]
Oi, @Wilson08 descupe pela demora. Executei o teste novamente com a versão 1.13 e o erro persiste.

**Comment by Wilson08** [comment]
@edusfc15 , tudo bem, irei analisar a situação.

**Comment by Wilson08** [comment]
@edusfc15, uma correção já está disponível na branch 'develop', realmente o método ScrollGrid não estava preparado para grids do tipo 'tget dados'.

- Para instalar a branch "develop"
>pip install git+https://github.com/totvs/tir.git@develop --upgrade

**Comment by edusfc15** [comment]
Ok , vou testar.

**Comment by Wilson08** [comment]
@edusfc15 , como foi identificado o erro e uma correção foi lançada na develop, iremos fechar Issue.
Caso tenha alguma dúvida por favor entre contato conosco pelo [Gitter](https://gitter.im/totvs-tir/General)
