### ISSUE TITLE
Erro tela de login após atualização do TIR e do Webapp

### ISSUE THREAD

**Issue by DSGsolucoes** [totvs/tir#1563]
**Describe the bug:**

Estou com um problema ao realizar o login. Após a atualização do webapp e do TIR para a nova versão. A tela trava e parece não reconhecer os campos de login e senha.

**To Reproduce:**

1. Teste realizar algum teste utilizando o TIR após as atualizações.
2. A tela trava e não realiza o login, segue prints e configurações do meu config.json:

    "Url": "http://hmlsrverp:10051/webapp/",
    "Browser": "Firefox",
    "Environment": "TST",
    "POUILogin": true,
    "User": "admin",
    "Password": "admin",
    "Language": "pt-br",
    "SkipEnvironment": false,
    "Headless": false,
    "DBDriver": "Oracle em OraClient12Home1",
    "DBServer": "DBORACLEERPH",
    "DBName": "ERPH",
    "DBUser": "USER_ERP_CONSULTA",
    "DBPassword": " ",
    "DBQOracleServer": "DBORACLEERPH:1521/ERPH",

**Expected behavior:**

O login ser realizado com sucesso.

**Screenshots:**

![error login](https://github.com/user-attachments/assets/661ef089-b488-4f50-aa68-f9127b3a5737)

![error webapp](https://github.com/user-attachments/assets/0c499256-1afe-4cba-b6d9-8e2a0c099475)

**Desktop:**
 - OS: Windows 11
 - Browser : Firefox
 - Version 131.0.3 (64-bits)

**Additional context**

Não.

**Comment by DSGsolucoes** [comment]
Boa tarde, segue evidencias solicitadas pela analista Renan Lacerda:

![01](https://github.com/user-attachments/assets/a6594673-add7-48fa-a99c-d537c938dafc)

![02](https://github.com/user-attachments/assets/e18e3d90-fa93-4171-acbd-196402bdbc87)

Desde já agradeço a atenção.

**Comment by renanllisboa** [comment]
Cliente relatou que após a atualização do webapp o problema foi solucionado.
