### ISSUE TITLE
Exemplo de script com IF/ELSE

### ISSUE THREAD

**Issue by alexrejulio** [totvs/tir#235]
É possível utilizar a ferramenta com um script com IF/ELSE ?

Meu problema é por exemplo utilizar uma rotina e verificar caso o registro exista poder analisar se um campo tem um valor e decidie pela exclusão do registro para proceder com uma nova inclusão.

Grato.

**Comment by renanllisboa** [comment]
Bom dia,

@alexrejulio você tentou utilizar o método GetValue() para coletar informação de um campo?

Veja se atende para está situação e nos retorne caso precise de mais alguma orientação.

Obrigado
