### ISSUE TITLE
Não consigo setar valor em campo DropDown

### ISSUE THREAD

**Issue by DMSantos752** [totvs/tir#245]
Fiz um case baseado no exemplo de inclusão de cliente pela rotina MATA030.
Não consegui atribuir valor ao campo A1_TIPO que é do tipo DropDown.
Ao fazer a atribuição do campo com o comando :

`self.oHelper.SetValue('A1_TIPO','F')`

aparece no console o seguinte :

> Looking for element: A1_LOJA
> Current field value: 01
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO
> Looking for element: A1_TIPO

Depois dá um erro :

```
======================================================================
FAIL: test_MATA030_CT001 (__main__.MATA030)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\SeleniumTeste\MATA030CASE001.py", line 26, in test_MATA030_CT001
    self.oHelper.SetValue('A1_TIPO','F')
  File "C:\Python38-32\lib\site-packages\tir\main.py", line 641, in SetValue
    self.__webapp.SetValue(field, value, grid, grid_number, ignore_case, row, name_attr, position)
  File "C:\Python38-32\lib\site-packages\tir\technologies\webapp_internal.py", line 1042, in SetValue
    self.input_value(field, value, ignore_case, name_attr, position, check_value)
  File "C:\Python38-32\lib\site-packages\tir\technologies\webapp_internal.py", line 1187, in input_value
    self.log_error(f"Could not input value {value} in field {field}")
  File "C:\Python38-32\lib\site-packages\tir\technologies\webapp_internal.py", line 3924, in log_error
    self.assertTrue(False, log_message)
AssertionError: False is not true : CT001 - Could not input value F in field A1_TIPO
```

**Comment by renanllisboa** [comment]
Boa noite,

Favor inspecionar a pagina e nos enviar a imagem, tanto da tela quanto a pagina HTML inspecionada.

Também a versão do release do Protheus e versão do webapp utilizado.

Obrigado.

**Comment by DMSantos752** [comment]
SMARTCLIENT WEB-APP VERSAO 4.3.1 - BUILD 170117A - WINDOWS X86 RELEASE 12.1.25
Build: 7.00.170117A-20190628 - 64 bits
Versão da lib: 20190705
Release do RPO: 12.1.025
Arquivos locais: ctree
Top DataBase: MSSQL


![tela](https://user-images.githubusercontent.com/58979830/71919217-e498da00-3162-11ea-8e22-e27adfdf34d6.JPG)

![inspetor 1](https://user-images.githubusercontent.com/58979830/71919225-e8c4f780-3162-11ea-8eb7-617bcce1ff2b.JPG)

**Comment by renanllisboa** [comment]
Se você inspecionar o elemento pressionando as teclas (Ctrl+Shift+C) e posicionar no campo A1_TIPO, ele deve exixbir o elemento dessa maneira, uma div contendo um select:
![image](https://user-images.githubusercontent.com/33421188/72002672-9ea54a00-3226-11ea-9d2e-7ba763cac6a7.png)

Poderia verificar, por favor?

**Comment by DMSantos752** [comment]
FIY : nos campos de texto simples a atribuição está funcionando bem.

![a1tipo](https://user-images.githubusercontent.com/58979830/72075583-d36edb00-32d2-11ea-9825-5492b7cd9276.JPG)

**Comment by renanllisboa** [comment]
Certo, o DOM está correto, o que você pode testar é a utilização do parâmetro "name_attr=True" no método SetValue, isso faz com que o elemento buscado seja considerado diretamente pelo atributo "name" dessa DIV. Ex:

self.oHelper.SetValue('A1_PESSOA','F', name_attr=True)

Faça um teste e nos retorne o resultado.

Obrigado.

**Comment by renanllisboa** [comment]
Está Issue será encerrada por falta de interação, caso o problema persista, pedimos que abra uma nova issue.

Obrigado
