### ISSUE TITLE
Remove Mask is not respecting masks setup

### ISSUE THREAD

**Issue by eternauta123** [totvs/tir#247]
A funcao remove mask nao respeita a mascara configurada para o Ambiente.
Para data, funciona, pois remove tanto . (formato russo) como "/" (formato nao russo).
Para valores nao funciona, pois remove o separador de milhar "." desrespeitando a mascara do ambiente.
Por default, nossa equipe informa os números na mascara esperada ("9999,99"), sem separador de milhar, mas campos preenchidos por validações ou gatilhos serão preenchidos com o conteúdo no formato configurado para o ambiente (no caso RUSSO com a mascara "999 999.99") o que vai remover o ponto (não avaliei o que acontece com o espaco como separador de milhar) e deixa o valor errado.
Checking code I evalualed that in FILLFGRID function we may have same issue, remove "," and not removing ".".

**Comment by Wilson08** [comment]
@eternauta, para entender melhor sobre esse caso preciso de algumas informações adicionais.
Os casos citados acima estão relacionados ao preenchimento de uma enchoice ou grid ? como
estão os valores na tela x valores no script? Qual método está tentando utilizar ?


- ENCHOICE:

>  VALOR NA TELA ( xxx.xxx.xxx,xx )        VALOR PASSADO NO SCRIPT ( xxx.xxx.xxx,xx )

- GRID:

> VALOR NA TELA ( xxx.xxx.xxx,xx )        VALOR PASSADO NO SCRIPT ( xxx.xxx.xxx,xx )

**Comment by eternauta123** [comment]
O problema é no grid, mas acredito que vai acontecer em qqer get.

Passado no script 9999,99 na tela 9 999.99
Crie a chave no seu ambiente e vai conseguir reproduzir em qqer campo numérico só debuge a remove mask e vai perceber rápido que está removendo o ponto (que no formato Brasil é separador de milhar e na Rússia é separador de decimais)
PICFORMAT=russian

**Comment by Wilson08** [comment]
@eternauta123, os valores de script e tela devem ser iguais.
Ainda sim mesmo que isso não seja respeitado internamente no TIR,  realizamos algumas tentativas para amenizar as diferenças entre as pictures existentes  removendo os caracteres "." e "," . 

>Como é possível ver nesse trecho de código retirado do método interno fill_grid(responsável pelo preenchimento de valores em grid):
> ~~~Python
> self.remove_mask(current_value).strip().replace(',','') != field_one.replace(',','')
> ~~~

Pelo que foi explicado a situação que pode estar ocorrendo internamente é uma comparação da seguinte forma  "999999" x "9 99999", isso retorna False e apresentara um erro.

Exemplo | Valores sem alteração | Como os valores estão sendo comparados pelo TIR |
--------- | ------------------------ | --------------------------------------------------------- |
Script     | 9999,99                       | 999999                                                                         |
Tela        | 9 999.99                      | 9 99999                                                                        |


- Você pode conseguir mais informações sobre essa situação nas notas do release 1.9.0
> https://github.com/totvs/tir/releases/tag/v1.9.0

**Comment by eternauta123** [comment]
Porque fechou? 
Essa é a mascara no idioma russo, a funcao removeMASK deveria eliminar o espaco...
O problema continua.
So que como a removemask não é usada só para números, a implementalção é um pouco mais compelxa. Deveria perceber que é um número antes de remover o espaço

**Comment by Wilson08** [comment]
@eternauta123 foi fechada por falta de interação, mas que bom que está com a gente ainda 👍 .
Vou reabrir a issue, essa questão ainda está sendo analisada e já estamos pensando em alterar o remove_mask mas sem afetar o usuário que deseja testar as mascaras.

**Comment by eternauta123** [comment]
Foi resolvido?

**Comment by renanllisboa** [comment]
Sairá no próximo release da master.

Já é possível testar utilizando a branch release/v1.20.4rc11.

Atenciosamente
