### ISSUE TITLE
Adicionar vcredist na instalação do ambiente.

### ISSUE THREAD

**Issue by luizhj** [totvs/tir#275]
Adicionar vcredist na instalação do ambiente, sem ele falta o cl.exe e o python não consegue instalar o pandas.

choco install vcredist140

**Comment by renanllisboa** [comment]
Bom dia,

A sugestão de instalação deste programa está relacionado ao instalador do TIR?

Poderia nos informar mais detalhes?

Obrigado.

**Comment by luizhj** [comment]
ao instalar o tir uma das dependências é o pandas e o ele exige que o compilador c++ esteja instalado para que ele possa ser compilado. sem ele não instala.

a ideia seria adicionar o compilador c++ necessário ao pandas no script de instalação.
na verdade acho que nem é o vcredist140 o certo.

**Comment by renanllisboa** [comment]
Boa tarde,

@luizhj , houve um problema nos 2 últimos releases do pandas, que de fato afetou este pacote no projeto do TIR. Nós fizemos o downgrade de versão para uma versão estável do pandas e já subimos no ultimo release. Faça a instalação do pacote utilizando o comando pip install tir_framework.

Quanto a opção de instalar essas dll's no ambiente do cliente, ficaria a cargo de uma unica opção que temos de instalação que é pelo instalador electron do TIR, este caso será avaliado a real necessidade.

Obrigado.
