### ISSUE TITLE
Cadastro de Produtos (Protheus) tem duas Pastas Cadastrais

### ISSUE THREAD

**Issue by cicerocruz** [totvs/tir#315]
Olá,

Quando quero  selecionar uma pasta  na  tela  eu  uso o comando:
self.oHelper.ClickFolder('Cadastrais')
self.oHelper.ClickFolder('C.Q.')

No caso da MATA010 temos  duas pastas Cadastrais uma  na  tela  principal e  outra no cadastro de Complemento de Produto,  como seleciono esta segunda pasta "Cadastrais"?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Wilson08** [comment]
@cicerocruz , atualize a sua versão do TIR para o release 1.15.12. O método ClickFolder agora tem o parâmetro **position** para mais detalhes acesse:
https://totvs.github.io/tir/webapp.html?highlight=clickfolder#tir.main.Webapp.ClickFolder
