### ISSUE TITLE
Erro em Script Exception (selenium.common.exceptions.Move)

### ISSUE THREAD

**Issue by Wilson08** [totvs/tir#325]
**Describe the bug**
Ao executar o script uma exception foi lançada.

@cicerocruz  
**To Reproduce**

**Expected behavior**

**Screenshots**
Não existe uma screenshot sobre o problema relatado.

@cicerocruz 
**Desktop (please complete the following information):**

**Additional context**
### Gitter - @cicerocruz :

> Olá, no MATA010 (Cadastro de Produto) para alguns Produtos ocorre o seguinte erro:
> 
> Looking for element: B1_COD
> Waiting blocker to continue...
> Current field value: 000000000000000
> 
> Warning (from warnings module):
> File "C:\Python36\lib\site-packages\pandas\core\generic.py", line 5303
> self[name] = value
> SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame.
> Try using .loc[row_indexer,col_indexer] = value instead
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
> Filling grid field: A5_FORNECE
> ERROR
> 
> ======================================================================
> ERROR: test_MATA010_CT003 (CASE02PRODUTO.MATA010)
> 
> Traceback (most recent call last):
> File "C:\Python36\lib\site-packages\tir\technologies\webapp_internal.py", line 3507, in fill_grid
> ActionChains(self.driver).move_to_element(selenium_column()).send_keys_to_element(selenium_column(), Keys.ENTER).perform()
> File "C:\Python36\lib\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
> self.w3c_actions.perform()
> File "C:\Python36\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
> self.driver.execute(Command.W3C_ACTIONS, enc)
> File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
> self.error_handler.check_response(response)
> File "C:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (60, 757) is out of bounds of viewport width (1536) and height (750)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Python36\lib\site-packages\tir\technologies\core\base.py", line 689, in send_keys
> element.send_keys(arg)
> File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
> 'value': keys_to_typing(value)})
> File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
> return self._parent.execute(command, params)
> File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
> self.error_handler.check_response(response)
> File "C:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.ElementNotInteractableException: Message: Element <td id="0" class="selected-cell"> is not reachable by keyboard
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "Z:\TIR\CARGADADOS\CASE02PRODUTO.py", line 76, in test_MATA010_CT003
> self.oHelper.LoadGrid()
> File "C:\Python36\lib\site-packages\tir\main.py", line 306, in LoadGrid
> self.__webapp.LoadGrid()
> File "C:\Python36\lib\site-packages\tir\technologies\webapp_internal.py", line 3338, in LoadGrid
> self.fill_grid(field, x3_dictionaries, initial_layer)
> File "C:\Python36\lib\site-packages\tir\technologies\webapp_internal.py", line 3511, in fill_grid
> self.send_keys(selenium_column(), Keys.ENTER)
> File "C:\Python36\lib\site-packages\tir\technologies\core\base.py", line 698, in send_keys
> actions.perform()
> File "C:\Python36\lib\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
> self.w3c_actions.perform()
> File "C:\Python36\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
> self.driver.execute(Command.W3C_ACTIONS, enc)
> File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
> self.error_handler.check_response(response)
> File "C:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.Move
> O interessante é que não gera nenhum arquivo de Log...

**Comment by renanllisboa** [comment]
Boa tarde, a correção para está não conformidade já encontra-se disponível na branch Master. Favor atualizar o TIR e realizar um novo teste.
Atualize utilizando o comando "pip install tir_framework"
TIR Release 1.15.11
Para verificar o release, abra o prompt de comando e digite "pip show tir_framework"

Atenciosamente.
