### ISSUE TITLE
Rotina MATA415-ORCAMENTOS SIGAFAT - no TIR nao SALVA e nao gera erro

### ISSUE THREAD

**Issue by fabiofurlanc** [totvs/tir#339]
bom dia, problema com o TIR e rotina MATA415-ORCAMENTOS, mesmo o script tendo a instrução de SALVAR o TIR não salva e também não gera nenhum erro segue evidência do processo, script e log em https://www.dropbox.com/s/zp91fbt4f6owuxs/evidencia%2001%20para%20totvs.rar?dl=0

**Comment by Wilson08** [comment]
Fabio, utilize o enconde UTF-8 em seus scripts.
> Tente utilizar o seu script da seguinte forma:
> ![image](https://user-images.githubusercontent.com/39556283/81810344-29f65b00-94f9-11ea-9364-db6a159c84c5.png)

**Comment by fabiofurlanc** [comment]
Boa tarde, efetuei o que solicitou e persiste o problema, veja que não salva e fica parado, anexo link da evidência em vídeo do final do processo demonstrando, tanto que o encode está como UTF-8 como as instruções que orientou no script, no aguardo...

https://www.dropbox.com/s/iliqkotadfuq1vk/evidencia%2003%20para%20totvs.rar?dl=0

**Comment by Wilson08** [comment]
Fabio, poderia enviar o arquivo CSV gerado no final da execução ?

**Comment by fabiofurlanc** [comment]
Bom dia, infelizmente não pois o TIR não gera o log uma vez que não conclui a operação fica parado evidência:
https://www.dropbox.com/s/oi15yeu2peykcac/evidencia%2004%20para%20totvs.rar?dl=0

**Comment by Wilson08** [comment]
Fabio, o log não foi gerado pois o timeout do método WaitHide por padrão é de 1200 segundos:
![image](https://user-images.githubusercontent.com/39556283/81936279-61800880-95c8-11ea-839d-874c0beef1c3.png)

Mesmo assim com a *evidência_04* tenho uma outra suspeita do que pode estar gerando o erro, poderia realizar um teste ?  altere o script para que o passo antes de realizar o clique no botão "*Salvar*" ele altere um campo da *enchoice* :
![image](https://user-images.githubusercontent.com/39556283/81936332-7a88b980-95c8-11ea-8423-3be95201fdd0.png)

**Comment by fabiofurlanc** [comment]
Olá Wilson, se fizer isso que orientou ai passa a gerar erro evidencias
https://www.dropbox.com/s/d8ftkqe270qxqaq/evidencia%2005%20para%20totvs.rar?dl=0

**Comment by fabiofurlanc** [comment]
Não seria mais produtivo, você simular o mesmo cenário ai, assim creio que agilizaria a solução

**Comment by Wilson08** [comment]
> Olá Wilson, se fizer isso que orientou ai passa a gerar erro evidencias
> https://www.dropbox.com/s/d8ftkqe270qxqaq/evidencia%2005%20para%20totvs.rar?dl=0

Realmente digitei um campo que não está presente na enchoice, foi um erro de digitação.

**Comment by Wilson08** [comment]
> Não seria mais produtivo, você simular o mesmo cenário ai, assim creio que agilizaria a solução

Infelizmente o erro exibido nas evidências não é reproduzido.

Preciso de algumas informações para tentar simular o erro que acontece em seu ambiente:
- Versão do WebApp.
- Versão do TIR.
-----------------------------------------------------------------------------
>Mesmo assim com a evidência_04 tenho uma outra suspeita do que pode estar gerando o erro, >poderia realizar um teste ? altere o script para que o passo antes de realizar o clique no botão >"Salvar" ele altere um campo da enchoice :

Além das informações vou precisar que adapte um dos exemplos disponíveis em nosso [repositório de scripts](https://github.com/totvs/tir-script-samples) ( ⚠️ Altere os dados do script de acordo com o seu ambiente):
- [EXEMPLO MATA415](https://github.com/totvs/tir-script-samples/blob/master/Protheus_WebApp/Modules/SIGAFAT/MATA415TESTCASE.py)

Após rodar esse script poderia postar o resultado ?

**Comment by fabiofurlanc** [comment]
Boa tarde, baseado no seu script em nosso script foi removida instrução entre loadgrid e salvar, e funcionou.
Observando que foi necessário retornar ao encode windows1252 para que funcione a pesquisa de ordens com acento, problema resolvido, obrigado.
