### ISSUE TITLE
Execução em modo `Silencioso`

### ISSUE THREAD

**Issue by wscardua** [totvs/tir#374]
Seria bem legal se os testes pudessem acontecer em modo `silencioso` sem a necessidade de abrir um browse, como o projeto utiliza o selenium talvës seja possível.

**Comment by renanllisboa** [comment]
Boa tarde @wscardua ,

O TIR comporta a execução em modo silencioso(headless) para isso basta colocar a opção "Headless: true" no arquivo config.json.
Ex:
   "Url": "http://localhost:2018/",
    "Browser": "firefox",
    "Environment": "P12.1.27",
    "Language": "pt-br",
    "User": "teste",
    "Password": "teste",
    "Headless": true,

Atenciosamente
