### ISSUE TITLE
SetButton não funciona nas opções dentro de 'Outras Ações'

### ISSUE THREAD

**Issue by wscardua** [totvs/tir#377]
Ola pessoal,

Percebi que não consigo 'clicar' nenhuma opção dento da botão 'Outas Ações'

```
        self.oHelper.SetButton("Outras Ações")
        self.oHelper.SetButton("Visualizar") 
```

![erro-click-excluir](https://user-images.githubusercontent.com/47982596/87829278-18149980-c855-11ea-945f-783e949350f8.PNG)

**Comment by renanllisboa** [comment]
Boa noite @wscardua , para os casos em que é necessário clicar em botão dentro de outras ações, o método SetButton suporta essa ação da seguinte maneira:

self.oHelper.SetButton("Outras Ações", "Visualizar") conforme descrito na documentação.

Segue o link da documentação deste método:
https://totvs.github.io/tir/webapp.html?highlight=setbutton#tir.main.Webapp.SetButton

Atenciosamente.
