### ISSUE TITLE
Problemas de instalação do PIP no Mac os 

### ISSUE THREAD

**Issue by fhfavaretto** [totvs/tir#443]
o pip de instalação no macOS não funciona da forma que deveria ao instalar as dependências a biblioteca pandas no build não termina e retorna inúmeros erros já tentei em dois macs diferentes e o resultado e o mesmo poderia me confirmar se o TIR e otimizado para outros sistemas além do Windows.

**Comment by renanllisboa** [comment]
Boa tarde,

@fhfavaretto , dependendo da versão do python, ela pode não estar homologada pela biblioteca do Pandas, acredito que até a versão 3.8 esteja homologado. Da uma olhada nisso.

Quanto a homologação do TIR entre plataformas, MAC de fato nunca homologamos, somente Windows e Linux estamos em estágio de homologação.

Atenciosamente

**Comment by fhfavaretto** [comment]
sim utilizo a versão homologada 3.8, porém no build do Tir_framework está dando como falha na biblioteca do pandas,
a previsão para homologação do MacOsx ?

**Comment by fhfavaretto** [comment]
nada ainda ?

**Comment by renanllisboa** [comment]
Bom dia @fhfavaretto ,

Não temos uma previsão de quanto vamos homologar algo para MacOS, mas aparentemente o seu erro está mais relacionado a dependências, visto que na versão 3.8 este erro permaneceu, poderia testar com a versão 3.7.9 do python?

Atenciosamente
