### ISSUE TITLE
Tela de login

### ISSUE THREAD

**Issue by Wilson08** [totvs/tir#467]
**Descrevendo o bug**

@sidinorris
> Simplesmente não insere a senha, o TIR fica "tentando" colocar ela até dar erro de login..
> Continua o problema da inserção do usuário e senha do Protheus, ora funciona, ora fica piscando ambos os campos até dar erro de login, ora consegue inserir apenas o usuário e fica piscando o cursor no campo da Senha. 

**Para reproduzir**
Não reproduzido ainda.

**Screenshots**
![image](https://user-images.githubusercontent.com/39556283/102535197-a43a1f80-4086-11eb-9470-120c8e596cd8.png)

**Informações:**
 - OS: WINDOWS?
 - Browser: Firefox 83.0 64bits
 - WEBAPP: 4.6.3 - BUILD 170117A - WINDOWS X64.
 - TIR: 1.17.38

**Informações adicionais**
Monitor Touch ?
Arquivo TESTSUITE.py?
Arquivo TESTCASE.py?

**Comment by sidinorris** [comment]
Olá!

Monitor não é Touch, uma tela LCD comum de 21 polegadas, fullHD.

Os arquivos TESTESUITE e TESTCASE são os disponibilizados no exemplo do repositório, que efetuam inserção de Cliente e Pedido de venda:

Nossa conexão atual:
  "Url": "http://hvq0yu.tst.protheus.totvscloud.com.br:8599/",
    "Browser": "Chrome",

Ela é um pouco lenta, talvez o tratamento a ser realizado na localização e preenchimento dos campos de senha e usuário tenha a ver com isso.

Att,

**Comment by Wilson08** [comment]
@sidinorris, agradecemos as informações adicionais. Infelizmente o browser Chrome ainda está sendo homologado estamos trabalhando para que ele possa ser considerado em breve.

Sobre o erro vamos confirmar somente mais algumas informações:

- O erro é reproduzido utilizando o Browser Firefox?
- A senha que está no arquivo de configuração (config.json) com a chave "Password" segue o mesmo padrão que os teste manuais sem diferença de letras minúsculas, maiúsculas ou acentuação e espaçamento ?

**Comment by sidinorris** [comment]
Sim, é reproduzido no Firefox também, 83.0 64bits.
Senha está no padrão.
Ora ocorre, ora não ocorre o problema. Ora nem o usuário é preenchido, o cursor pisca em ambos os campos e clica em Entrar mesmo sem tê-los preenchido.

**Comment by Wilson08** [comment]
@sidinorris, realizei um teste utilizando o ambiente "http://hvq0yu.tst.protheus.totvscloud.com.br:8599/":
![Captura de tela de 2020-12-18 11-22-22](https://user-images.githubusercontent.com/39556283/102642197-1587da00-413c-11eb-8131-2cc5ebd4b845.png)

Como pode ver na imagem o TIR conseguiu preencher o usuário: "admin" e a senha: "1234" com isso vou lenvantar mais algumas questões:
- Existe mais de um Python instalado na máquina ?
- O Script está sendo executado via Command Line ou  IDE ?
- O Python atual tem o pacote Anaconda ou semelhante instalado ?
- Qual o retorno do comando "pip list"?

**Comment by sidinorris** [comment]
Olá. 
1 - Temos apenas o Python 3.8.0 
2 - Está sendo utilizado via IDE Visual Studio Code 1.52.0 
3 - Não tem Anaconda ou outro pacote semelhante.
4 - Temos o seguinte resultado ao executar pip list:
astroid           2.4.2
Babel             2.9.0
backcall          0.2.0
beautifulsoup4    4.9.3
bradocs4py        1.3.1.0
certifi           2020.12.5
chardet           3.0.4
colorama          0.4.4
csscompressor     0.9.5
decorator         4.4.2
enum34            1.1.10
idna              2.10
ipykernel         5.3.4
ipython           7.19.0
ipython-genutils  0.2.0
isort             5.6.4
jedi              0.17.2
Jinja2            2.11.2
jupyter-client    6.1.7
jupyter-core      4.7.0
lazy-object-proxy 1.4.3
libsass           0.20.1
Markdown          3.3.3
MarkupSafe        1.1.1
mccabe            0.6.1
numpy             1.19.4
pandas            1.0.1
parso             0.7.1
pickleshare       0.7.5
pip               20.3.1
prompt-toolkit    3.0.8
psutil            5.7.3
Pygments          2.7.2
pylint            2.6.0
pyodbc            4.0.30
python-dateutil   2.8.1
pytz              2020.4
pywin32           300
PyYAML            5.3.1
pyzmq             20.0.0
requests          2.25.0
selenium          3.8.0
setuptools        41.2.0
six               1.15.0
soupsieve         2.1
tir-framework     1.17.38
toml              0.10.2
tornado           6.1
traitlets         5.0.5
urllib3           1.26.2
wcwidth           0.2.5
wrapt             1.12.1

**Comment by Wilson08** [comment]
@sidinorris, realizei alguns testes com a versão mais estável do python 38(**python 3.8.7**) e **numpy==1.19.3**.
![image](https://user-images.githubusercontent.com/39556283/102826738-087b1d00-43c0-11eb-8619-c9bc2e1f8c12.png)

Por favor realize mais um teste seguindo essa versão de python e dependências.

**Comment by sidinorris** [comment]
Realizada atualização para as Releases sugeridas. Python 3.8.7 numpy 1.19.3 
Continua incorreto, piscando o cursor em ambos os campos de login, e após alguns segundos ocorrendo erro de login.
Aparentemente tem haver com algum timeout, no debug aparecem diversas linhas com a descrição:
Waiting blocker to continue...
Waiting blocker to continue...
Waiting blocker to continue...
Waiting blocker to continue...

**Comment by Wilson08** [comment]
@sidinorris, por favor anexar o log-csv gerado na execução desse teste, toda a informação que sai no console do vs-code( stdout / stderr) e também a imagem gerada.

Poderia também adicionar as seguintes informações:
- Execute o comando "where python" no prompt de comandos do windows e anexe o resultado.
- Adicione um screenshot com todas as variáveis de ambiente(usuário e sistema) do Windows, caso não queira deixar essa informação pública pode enviar esse screenshot no chat privado do Gitter.
