### ISSUE TITLE
Update Chrome Driver and/or improve documentation

### ISSUE THREAD

**Issue by Danielgmelo** [totvs/tir#515]
**Is your feature request related to a problem? Please describe.**

The chrome driver that comes in the lib is not always compatible with the chrome version installed on the machine.

I downloaded and installed the TIR following the installation guide ([here](https://github.com/totvs/tir/tree/9917906cd3f172b7756d6aa4df46b4c6f99c9d20#installation)) and I did a simple login test, but the chrome didn't open. The following error returned:

`'WebappInternal' object has no attribute 'driver'`

**Describe the solution you'd like**
I checked the courrent version of my chrome and [downloaded](https://chromedriver.chromium.org/downloads) the correct driver version. After, I saved it [here](https://github.com/totvs/tir/tree/master/tir/technologies/core/drivers/windows) and tested againd... it worked normally.

Could you put in the documentation that it is necessary to check the crhome version and the driver version?

**Comment by renanllisboa** [comment]
Boa tarde, @Danielgmelo .

Conforme relatado no gitter, hoje não atualizamos o driver do chrome devido a não estar homologado na ferramenta.

Assim que começarmos a homologar o chrome, informamos no Gitter.

Atenciosamente.
