### ISSUE TITLE
CheckHelp clicando em botão mesmo não achando

### ISSUE THREAD

**Issue by edhornberger** [totvs/tir#632]
**Describe the bug**
Estou usando o [ CheckHelp(text='', button='', text_help='', text_problem='', text_solution='', verbosity=False) ] da seguinte forma: 

					if aCamposOrd[nfields][0] == "A1_COD":
						cCodigo = csv_content_dictionary[aCamposOrd[nfields][0]][row]
						self.oHelper.SetValue(aCamposOrd[nfields][0], csv_content_dictionary[aCamposOrd[nfields][0]][row])

					elif aCamposOrd[nfields][0] == "A1_CGC":
						self.oHelper.SetValue(aCamposOrd[nfields][0], csv_content_dictionary[aCamposOrd[nfields][0]][row])
						self.oHelper.CheckHelp("informado já foi utilizado no cliente", button="Aceitar")
							
					else:
						self.oHelper.SetValue(aCamposOrd[nfields][0], csv_content_dictionary[aCamposOrd[nfields][0]][row])

**To Reproduce**
1. Ao gerar um script para inclusão de clientes, caso o registro de teste tiver um CNPJ ou CPF já cadastrado no Sistema apresenta tela de msg para Aceitar ou Cancelar o cadastro;
2. Nos casos que se apresenta a tela é realizado o Click no button informado:
2022-05-06 16:29:53,171-INFO:: Checking Help on screen: informado j� foi utilizado no cliente
2022-05-06 16:29:55,727-INFO:: Help on screen Checked: informado j� foi utilizado no cliente
2022-05-06 16:29:56,624-INFO:: Clicking on Aceitar
3. Nos casos onde não se apresenta deveria passar sem realizar o Click no button informado:
2022-05-06 16:32:43,288-INFO:: Checking Help on screen: informado j� foi utilizado no cliente
2022-05-06 16:32:45,423-INFO:: Couldn't find: 'informado j� foi utilizado no cliente', text on display window is: 'Clientes - INCLUIR '
2022-05-06 16:32:46,193-INFO:: Clicking on Aceitar
4. Como apresentado acima mesmo não encontrando é realizado o Click

**Expected behavior**
Caso não encontre o objeto Help na tela não acionar o Click no button

**Screenshots**
![image](https://user-images.githubusercontent.com/88506897/167206790-3ff0bb95-1434-48c9-9bbc-1d7cf4e3e34e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 100.0 (64-bits)

**Additional context**

**Comment by renanllisboa** [comment]
Bom dia, @edhornberger .

Conseguiu contornar este caso, quer entrar em contato para avaliarmos este caso?

Pode nos chamar através do Gitter para mais detalhes.
Segue:
Gitter: https://gitter.im/totvs-tir/General
