### ISSUE TITLE
Instalacao MacOs M1 apresenta ERRO NUMPY

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tir#778]
Boa tarde Prezados,

Estou tentando instalar no MacOS Monterey 12.4 e está apresentando **ERRO NUMPY** porém o ele já está instalado e diz que não existe.
![Captura de Tela 2022-07-04 às 17 39 52](https://user-images.githubusercontent.com/42280023/177214563-71e6ff83-e05a-48af-9b8f-7347b0049143.png)

![Captura de Tela 2022-07-04 às 17 40 40](https://user-images.githubusercontent.com/42280023/177214568-6643bf2d-960f-48ed-979b-4328edbe604f.png)

**Comment by maximinocastro** [comment]
Tentei instalar no Windows e apresentou o mesmo do MACOS.

Versão do Python > pip 9.0.3 from c:\python36\lib\site-packages (python 3.6)

**Comment by marlondutra** [comment]
Mesmo erro aqui, tentando no windows. Acredito que o problema esteja na dependência de uma versão especifica do numpy...quando tento instalar esta versão específica apresenta o mesmo erro.

**Comment by marlondutra** [comment]
consegui instalar removendo as dependências e instalando as mesmas de forma manual posteriormente. 

utilize o comando pip install tir-framework --no-dependencies

**Comment by maximinocastro** [comment]
Descobri o problema por que estava dando bastante problemas na instalação, precisa estar na versão python 3.7.9 por isso não estava dando certo, após desinstalar e reinstalar novamente deu certo porém ao executar o projeto tanto no windows quanto no mac, tá apresentando o erro do PANDAS não instalado.

![Captura de Tela 2022-07-05 às 15 30 30](https://user-images.githubusercontent.com/42280023/177394094-3f68e3fa-87ea-4c73-a5fe-aea0d0eea5fb.png)

**Comment by renanllisboa** [comment]
@maximinocastro .

As plataformas homologadas são Windows e Linux, na versão 3.7.9 do Python.

Você gostaria de entrar em contato pelo Gitter para entendermos a sua necessidade?

Segue link:
Gitter: https://gitter.im/totvs-tir/General

**Comment by maximinocastro** [comment]
@renanllisboa já entrei em contato e tem 3 publicações minhas no Glitter porém ninguém respondeu isso já vai fazer 6 meses rs
TOTVS TIR é uma ferramenta poderosa porém sem suporte na comunidade e sem ninguém pra explicar se torna um produto ruim e obsoleto. 
Por que também tive diversos problemas na instalação do Windows e niguém tirou minhas dúvidas então larguei de mão..

**Comment by renanllisboa** [comment]
Boa tarde, @maximinocastro .

Se teve alguma interação que deixamos de responder, peço desculpas, mas a ideia do canal no Gitter, é de ser uma comunidade. Então tanto o time quanto a própria comunidade pode responder as dúvidas postadas.

Quanto a este problema do pandas pode ter falhado a instalação da dependência, a sugestão é instalar novamente.

Se tiver alguma outra dúvida quanto a instalação e utilização pode nos acionar por lá.

Atenciosamente
